graph LR
    User
    User([👤 User])
    AskData[/AskData/]
    MCPServer["MCP Server"]
    User <--> Copilot <--> MCPServer <--> AskData
    AskData --> KernelMemory["<b>KernelMemory</b>"]
    KernelMemory --> Ollama((Ollama))
    KernelMemory --> QDrant[(QDrant)]
    KernelMemory --> FileStorage[[FileStorage]]
