sequenceDiagram
    actor User
    participant vscode as vscode Copilot<br>(agent mode)
    participant AskData as AskData<br> MCP Tool
    participant KernelMemory
    participant Ollama
    participant QDrant as QDrant DB
    participant FileStorage

    User->>vscode: Query
    vscode->>vscode: LLM processed query
    vscode->>AskData: MCP tool call \w query
    AskData->>KernelMemory: SearchAsync(query)
    KernelMemory->>Ollama: Query
    Ollama-->>KernelMemory: Embedding
    KernelMemory->>QDrant: Search embedding
    QDrant-->>KernelMemory: Memories
    KernelMemory-->>AskData: search results:<br>chunks + citations
    AskData->>AskData: Process results
    AskData->>KernelMemory: (Optional) ExportFileAsync()
    KernelMemory->>FileStorage: Retrieve files
    FileStorage-->>KernelMemory: Files
    KernelMemory-->>AskData: Files
    AskData->>AskData: Process files
    AskData-->>vscode: MCP tool response
    vscode->>vscode: RAG
    vscode-->>User: Output